### ISSUE TITLE
Docs: the effect of `image=false` are not totally clear

### ISSUE THREAD

**Issue by lmbarros** [balena-os/leviathan#619]
First, the quick start guide says this

> [Optional] Set the image property to the `false` in the config.json file if you don't wish to provide a balenaOS image. The e2e test won't explicitly be needing a balenaOS image to run the test.

I'd avoid an optional step like this on the quick start guide, because someone starting with Leviathan doesn't have yet the knowledge to decide if they want or not to perform this optional step. The implications are not clear for a beginner.

Second, the `config.js` reference says

> If you don't want to upload an image, set the image property to `false`. For example: To run the e2e test suite, you don't need to upload an image.

Now, unless I misunderstood, what really happens with `false` is that a default image is downloaded from the cloud and send to the worker. So it will be faster to actually set a valid image, because this would avoid the download step. (Again, I am not I really understood how this works, but I think that's what happened when running the e2e tests on a QEMU worker).

**Comment by vipulgupta2048** [comment]
I agree with your first point, the false option removed the false option entirely from the Getting Started guide in order to keep things super simple for someone starting up. 

On your second point, here's what actually happens. The e2e suite is a diagnostic suite to check if the leviathan worker is working and set up correctly. The balenaOS image used in this test is irrelevant and doesn't matter because the functionality being tested is not of the image but of the worker instead. Hence, we created the false option so folks don't need to upload an image now instead the test suite itself downloads an image to test the worker with minimal configuration. As you see this context is quite to compress and pack in the documentation so I am thinking of this as a solution: https://www.flowdock.com/app/rulemotion/p-testbot/threads/kri63-MNtU4_c4tq2Jxi6uNnSY0
